package com.bolimot.mindtheclub.webrtc.group

import android.util.Base64
import com.bolimot.mindtheclub.functions.debugLine
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * The call key and the two small things it protects outside the media itself.
 *
 * A group call has one symmetric key, generated by whoever starts it and handed
 * to each participant inside the call invitation. That invitation already
 * travels sealed to the recipient's identity key (see FcmMessageSender), so the
 * key is delivered over the same channel the app's messages use and never
 * touches Cloudflare.
 *
 * Besides the video frames, the key seals the one human-readable field in a
 * room roster: who is behind a tile. Without it the relay hosting the room would
 * learn the guest list of every call.
 */
object CallCrypto {

    private const val IV_BYTES = 12
    private const val TAG_BITS = 128

    private val random = SecureRandom()

    /** A fresh 256-bit call key. */
    fun newKey(): ByteArray = ByteArray(32).also { random.nextBytes(it) }

    fun encodeKey(key: ByteArray): String = Base64.encodeToString(key, Base64.NO_WRAP)

    fun decodeKey(encoded: String): ByteArray? = try {
        Base64.decode(encoded, Base64.NO_WRAP)
    } catch (e: Exception) {
        debugLine("CallCrypto", "Bad call key: ${e.message}")
        null
    }

    /** AES-GCM, random IV prefixed to the ciphertext. */
    fun seal(key: ByteArray, plaintext: String): String {
        return try {
            val iv = ByteArray(IV_BYTES).also { random.nextBytes(it) }
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(Cipher.ENCRYPT_MODE, SecretKeySpec(key, "AES"), GCMParameterSpec(TAG_BITS, iv))
            val body = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
            Base64.encodeToString(iv + body, Base64.NO_WRAP)
        } catch (e: Exception) {
            debugLine("CallCrypto", "seal failed: ${e.message}")
            ""
        }
    }

    fun open(key: ByteArray, sealed: String): String? {
        if (sealed.isEmpty()) return null
        return try {
            val raw = Base64.decode(sealed, Base64.NO_WRAP)
            if (raw.size <= IV_BYTES) return null
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(
                Cipher.DECRYPT_MODE,
                SecretKeySpec(key, "AES"),
                GCMParameterSpec(TAG_BITS, raw, 0, IV_BYTES)
            )
            String(cipher.doFinal(raw, IV_BYTES, raw.size - IV_BYTES), Charsets.UTF_8)
        } catch (e: Exception) {
            debugLine("CallCrypto", "open failed: ${e.message}")
            null
        }
    }
}
